name: ⛽ Bensa Price Scraper

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 */4 * * *' # Run every 4 hours
  workflow_dispatch: # Allow manual trigger

permissions:
  contents: write

jobs:
  scraping-prices:
    name: 💸 Scraping-Prices
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '22'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build Bot
        run: npm run build:bot

      - name: Run Scraper
        run: npm run start:bot
        env:
          FIREBASE_SERVICE_ACCOUNT_KRUGOU_BENSA: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KRUGOU_BENSA }}
          VITE_FIREBASE_PROJECT_ID: ${{ secrets.VITE_FIREBASE_PROJECT_ID }}

      - name: Commit and push updated prices
        if: success()
        run: |
          git config --global user.name "Bensa Bot"
          git config --global user.email "bot@bensa.fi"
          git add web/public/api/prices.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "chore(data): sync latest gas prices [skip ci]" && git push)
